# ========================
# CONFIGURACIÓN DEL SERVER
# ========================
server:
  port: 8080
  servlet:
    context-path: /

# ========================
# Url de la API externa
# ========================
pokeapi:
  base-url: https://pokeapi.co/api/v2/pokemon/

# ========================
# CONFIGURACIÓN DE LA BASE DE DATOS
# ========================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemondb
    username: postgres_user
    password: tu_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
